apiVersion: 1

datasources:
  - name: LocalStack
    type: cloudwatch
    jsonData:
      authType: static
      defaultRegion: us-east-1
      endpoint: http://localstack_main:4566
    secureJsonData:
      accessKey: test
      secretKey: test
    version: 1
    readOnly: false
    editable: true