Description: LocalStack CloudWatch Logs setup
Outputs:
  SharedKMSKeyArn:
    Description: KMS Key ARN for encryption
    Export:
      Name: !Sub '${AWS::StackName}-KMSKeyArn'
    Value: !GetAtt 'CloudWatchLogKey.Arn'
Resources:
  CloudWatchLogKey:
    Properties:
      Description: KMS Key for CloudWatch Log Group Encryption
      EnableKeyRotation: true
      Enabled: true
      PendingWindowInDays: 7
    Type: AWS::KMS::Key
  CloudWatchLogKeyAlias:
    Properties:
      AliasName: alias/cloudgrindset-logs
      TargetKeyId: !Ref 'CloudWatchLogKey'
    Type: AWS::KMS::Alias
  DemoLogGroup:
    Properties:
      KmsKeyId: !GetAtt 'CloudWatchLogKey.Arn'
      LogGroupName: cloudgrindset2026-logs
      RetentionInDays: 14
    Type: AWS::Logs::LogGroup
  DemoLogStream:
    Properties:
      LogGroupName: !Ref 'DemoLogGroup'
      LogStreamName: demo-stream
    Type: AWS::Logs::LogStream

