Description: DNS for CloudGrindset2026 - Route 53
Outputs:
  HostedZoneId:
    Description: The ID of the Private Hosted Zone
    Export:
      Name: GrindsetHostedZone-ID
    Value: !Ref 'InternalHostedZone'
Resources:
  ApiRecord:
    HostedZoneId: !Ref 'InternalHostedZone'
    Name: api.grindset.local.
    ResourceRecords:
      - map.grindset.local.
    TTL: '300'
    Type: CNAME
  InternalHostedZone:
    Properties:
      HostedZoneConfig:
        Comment: DNS (Route53) for the CloudGrindset2026 repo
      Name: grindset.local
      VPCs:
        - VPCId: !ImportValue 'GrindsetVPC-ID'
          VPCRegion: us-east-1
    Type: AWS::Route53::HostedZone
  MapRecord:
    HostedZoneId: !Ref 'InternalHostedZone'
    Name: map.grindset.local.
    ResourceRecords:
      - 10.0.1.10
    TTL: '300'
    Type: A

