Description: 'Simplified EC2: Direct Access (LocalStack Compatible)'
Parameters:
  InstanceType:
    Default: t3.nano
    Type: String
Resources:
  WebServerInstance:
    Properties:
      IamInstanceProfile: !ImportValue 'iam-InstanceProfileName'
      ImageId: ami-fake-local
      InstanceType: !Ref 'InstanceType'
      SecurityGroupIds:
        - !Ref 'WebServerSG'
      SubnetId: !Select
        - 0
        - !Split
          - ','
          - !ImportValue 'GrindsetPublicSubnets-List'
      Tags:
        - Key: Name
          Value: Grindset-Web-Server
      UserData: !Base64 "#!/bin/bash\napt update\napt install -y nginx\n"
    Type: AWS::EC2::Instance
  WebServerSG:
    Properties:
      GroupDescription: Allow Direct HTTP access for LocalStack testing
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          Description: Allow HTTP traffic from anywhere
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
      Tags:
        - Key: Name
          Value: Web-Server-SG
      VpcId: !ImportValue 'GrindsetVPC-ID'
    Type: AWS::EC2::SecurityGroup

