Description: Baseline IAM setup for LocalStack for myself
Resources:
  AddMKToAdmins:
    Properties:
      GroupName: !Sub '${AWS::StackName}-Admins'
      Users:
        - !Sub '${AWS::StackName}-MK'
    Type: AWS::IAM::UserToGroupAddition
  AdminsGroup:
    Properties:
      GroupName: !Sub '${AWS::StackName}-Admins'
    Type: AWS::IAM::Group
  AdminsManagedPolicy:
    Properties:
      Groups:
        - !Sub '${AWS::StackName}-Admins'
      ManagedPolicyName: !Sub '${AWS::StackName}-AdminsAdministratorAccess'
      PolicyDocument:
        Statement:
          - Action: '*'
            Effect: Allow
            Resource: '*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy
  MKUser:
    Properties:
      UserName: !Sub '${AWS::StackName}-MK'
    Type: AWS::IAM::User

