Description: Baseline IAM setup with an EC2 Role for LocalStack
Outputs:
  WebServerInstanceProfileName:
    Export:
      Name: !Sub '${AWS::StackName}-InstanceProfileName'
    Value: !Ref 'WebServerInstanceProfile'
Resources:
  AddMKToAdmins:
    Properties:
      GroupName: !Sub '${AWS::StackName}-Admins'
      Users:
        - !Sub '${AWS::StackName}-MK'
    Type: AWS::IAM::UserToGroupAddition
  AdminsGroup:
    Properties:
      GroupName: !Sub '${AWS::StackName}-Admins'
    Type: AWS::IAM::Group
  AdminsManagedPolicy:
    Properties:
      Groups:
        - !Sub '${AWS::StackName}-Admins'
      ManagedPolicyName: !Sub '${AWS::StackName}-AdminsAdministratorAccess'
      PolicyDocument:
        Statement:
          - Action:
              - ec2:*
              - s3:*
              - iam:*
              - cloudwatch:*
              - vpc:*
              - dynamodb:*
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: 'true'
            Effect: Allow
            Resource: '*'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy
  MKUser:
    Properties:
      UserName: !Sub '${AWS::StackName}-MK'
    Type: AWS::IAM::User
  WebServerInstanceProfile:
    Properties:
      InstanceProfileName: !Sub '${AWS::StackName}-EC2-Profile'
      Roles:
        - !Ref 'WebServerRole'
    Type: AWS::IAM::InstanceProfile
  WebServerRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - s3:Get*
                  - s3:List*
                Effect: Allow
                Resource:
                  - arn:aws:s3:::regional-map-2024-website
                  - arn:aws:s3:::regional-map-2024-website/*
            Version: '2012-10-17'
          PolicyName: S3ReadAccess
      RoleName: !Sub '${AWS::StackName}-WebServerRole'
    Type: AWS::IAM::Role

