Description: Multi-AZ Networking Layer for CloudGrindset2026
Outputs:
  PrivateSubnetIds:
    Description: List of Private Subnet IDs
    Export:
      Name: GrindsetPrivateSubnets-List
    Value: !Join
      - ','
      - - !Ref 'PrivateSubnetAZ1'
        - !Ref 'PrivateSubnetAZ2'
  PublicSubnetIds:
    Description: List of Public Subnet IDs
    Export:
      Name: GrindsetPublicSubnets-List
    Value: !Join
      - ','
      - - !Ref 'PublicSubnetAZ1'
        - !Ref 'PublicSubnetAZ2'
  VpcId:
    Description: The ID of the VPC
    Export:
      Name: GrindsetVPC-ID
    Value: !Ref 'MainVPC'
Resources:
  InternetGateway:
    Properties:
      Tags:
        - Key: Name
          Value: Grindset-IGW
    Type: AWS::EC2::InternetGateway
  MainVPC:
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: Grindset-VPC
    Type: AWS::EC2::VPC
  PrivateSubnetAZ1:
    Properties:
      AvailabilityZone: us-east-1a
      CidrBlock: 10.0.10.0/24
      Tags:
        - Key: Name
          Value: Private-Subnet-us-east-1a
      VpcId: !Ref 'MainVPC'
    Type: AWS::EC2::Subnet
  PrivateSubnetAZ2:
    Properties:
      AvailabilityZone: us-east-1b
      CidrBlock: 10.0.11.0/24
      Tags:
        - Key: Name
          Value: Private-Subnet-us-east-1b
      VpcId: !Ref 'MainVPC'
    Type: AWS::EC2::Subnet
  PublicAssocAZ1:
    Properties:
      RouteTableId: !Ref 'PublicRouteTable'
      SubnetId: !Ref 'PublicSubnetAZ1'
    Type: AWS::EC2::SubnetRouteTableAssociation
  PublicAssocAZ2:
    Properties:
      RouteTableId: !Ref 'PublicRouteTable'
      SubnetId: !Ref 'PublicSubnetAZ2'
    Type: AWS::EC2::SubnetRouteTableAssociation
  PublicRoute:
    DependsOn: VPCGatewayAttachment
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref 'InternetGateway'
      RouteTableId: !Ref 'PublicRouteTable'
    Type: AWS::EC2::Route
  PublicRouteTable:
    Properties:
      Tags:
        - Key: Name
          Value: Public-RT
      VpcId: !Ref 'MainVPC'
    Type: AWS::EC2::RouteTable
  PublicSubnetAZ1:
    Properties:
      AvailabilityZone: us-east-1a
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public-Subnet-us-east-1a
      VpcId: !Ref 'MainVPC'
    Type: AWS::EC2::Subnet
  PublicSubnetAZ2:
    Properties:
      AvailabilityZone: us-east-1b
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public-Subnet-us-east-1b
      VpcId: !Ref 'MainVPC'
    Type: AWS::EC2::Subnet
  VPCGatewayAttachment:
    Properties:
      InternetGatewayId: !Ref 'InternetGateway'
      VpcId: !Ref 'MainVPC'
    Type: AWS::EC2::VPCGatewayAttachment

