Description: Local NGINX server simulation for static site without AWS on WSL
Outputs:
  InstanceId:
    Description: NGINX WebServer
    Value: !Ref 'WebServer'
Parameters:
  InstanceType:
    Default: t3.nano
    Description: Instance type
    Type: String
Resources:
  WebSG:
    Properties:
      GroupDescription: Allow HTTP/SSH
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: '0.0.0.0/0'
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
    Type: AWS::EC2::SecurityGroup
  WebServer:
    Properties:
      ImageId: ami-fake-local
      InstanceType: !Ref 'InstanceType'
      SecurityGroups:
        - !Ref 'WebSG'
      UserData: "#!/bin/bash\napt update\napt install -y nginx\nsystemctl enable nginx\nsystemctl start nginx\n"
    Type: AWS::EC2::Instance

