Description: LocalStack S3 bucket for regional-map-2024 hosting
Outputs:
  BucketName:
    Description: S3 bucket for regional-map-2024
    Value: !Ref 'RegionalMap2024Bucket'
Resources:
  RegionalMap2024Bucket:
    Properties:
      BucketName: regional-map-2024-website
      LoggingConfiguration:
        DestinationBucketName: !Ref 'ALBLogBucket'
        LogFilePrefix: s3-access-logs/regional-map/
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html
    Type: AWS::S3::Bucket

