Description: LocalStack S3 bucket for regional-map-2024 hosting
Outputs:
  BucketName:
    Description: S3 bucket for regional-map-2024
    Value: !Ref 'RegionalMap2024Bucket'
Resources:
  RegionalMap2024Bucket:
    Properties:
      BucketName: regional-map-2024-website
      WebsiteConfiguration:
        IndexDocument: index.html
    Type: AWS::S3::Bucket

