name: Checkov Security Scan
on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  checkov:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Graphviz
        run: sudo apt-get install -y graphviz
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Generate Templates
        run: |
          pip install troposphere
          chmod +x lab_scripts/legacy/generate_templates.sh
          for file in iac/*.py; do
            ./lab_scripts/legacy/generate_templates.sh "$file"
          done
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: yaml/
          framework: cloudformation
          soft_fail: false