name: CI/CD Pipeline Orchestrator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # 1. The Gatekeeper: Runs Pylint first
  lint:
    name: Lint IaC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pylint
        run: |
          pylint iac/*.py

  # 2. The Security Guard: Runs only if Lint passes
  checkov:
    name: Security Scan
    needs: lint
    uses: ./.github/workflows/check.yml

  # 3. The Deployer: Runs only if the Security Scan passes
  deploy:
    name: LocalStack Deploy
    needs: checkov
    uses: ./.github/workflows/deploy.yml